language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: perclasson
  password:
    secure: gkueSNadQSLwzGKzAohV+sUuOyPYPRCF9jkpe9l7DNg2x/vG0yH+v+0yIj5swU7fcXvxYTXEDyI4VKxk+BtthTKXFXcBINShv4MuRcUEaRK5Fkr/hh+Q50kWyGxtnJeXBtN7cO+/R4XjenWiySErvlNLyMAHDyBTYkWtFgyyYHqDfoH1XE3LVP0T1ArrJAo4pwSkfhryKcBOr9/VOvYnNWpYXwmF53WF0hemZARIwq9Cn1B++Z8q+mRFem9h8ZIpQpIPIGnCdLOqj+4PZlKnEtW7Z0R50uXFGXOfdHjPaMwjCzoi1TDbEupjX7A1s0GOKcm06cVT/CW6hyrjKOn3oeotMbUATYea4/9f7/7mjRnBdtyYjbA09SKqpsFkN01P7sScd5xPj+nGncvjDZiSNwjd5Af6Vj8+uHgitBRZF2zfE8R5OtqyrDJDNuCGOmindNMaFpo4scuYzZ2gDdviQefCRHS7GL207+DmlD/0riihBLkL8YSdxNKZHfKPyA5RjUhbQD5a0PhaGY56qBGCJZutIm/xc22sd+oeyNqfrxHz9SG5iqejZRJWM5Pavo9IIT3Yu8hFGOxMK73cz+DWGrG22JxA5+OX/6t+jq2NE6uxfz2X7lva2+cVKVSfY2Uxim+h+cySdW0160/H7hD+iSysNFDcJiwLL6xkOkS2jvw=
  on:
    tags: true
    repo: perclasson/deflaker
    python: 3.6
